apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: unicredit-demo-pipeline-
spec:
  pipelineRef:
    name: "demo-pipeline-retry"
  params:
    - name: filename
      value: README.json
    - name: url
      value: https://api.npoint.io/e1ce6e7e3038ea97d6d9
    - name: transform-path
      value: "readme.csv"
  workspaces:
    - name: shared-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
