---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/categories: CLI
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/platforms: linux/amd64,linux/s390x,linux/ppc64le
    tekton.dev/tags: download
  labels:
    app.kubernetes.io/version: "0.1"
  name: wget
spec:
  description: This task uses wget to download files from the internet to a workspace.
  params:
    - default: ""
      description: The url we want to download file from
      name: url
      type: string
    - default: []
      description: The directory path we want to save file to
      name: diroptions
      type: array
    - default: []
      description: The arguments to pass to wget
      name: options
      type: array
    - default: ""
      description: The filename we want to change our file to
      name: filename
      type: string
    - default: quay.io/khrm/wget:latest
      description: The wget docker image to be used
      name: wget-option
      type: string
  steps:
    - args:
        - $(params.options[*])
        - $(params.url)
        - $(params.diroptions[*])
      command:
        - wget
      image: $(params.wget-option)
      name: wget
  workspaces:
    - description: The folder where we write the wget'ed file to
      name: wget-workspace
